// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaIgreja.Infrastructure.Data;

#nullable disable

namespace SistemaIgreja.Infrastructure.Migrations
{
    [DbContext(typeof(SistemaIgrejaDbContext))]
    [Migration("20260206204124_AdicionarHubCasas")]
    partial class AdicionarHubCasas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.CategoriaMidia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasMidias");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.CategoriaNoticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasNoticias");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.ConfiguracaoMensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiasAposVisita")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HorarioEnvio")
                        .HasColumnType("time");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TextoMensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesMensagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiasAposVisita = 1,
                            HorarioEnvio = new TimeSpan(0, 10, 0, 0, 0),
                            Nome = "Boas-vindas",
                            TextoMensagem = "Olá {Nome}! Que alegria ter você conosco na igreja! Esperamos vê-lo novamente em breve. Deus abençoe!"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiasAposVisita = 7,
                            HorarioEnvio = new TimeSpan(0, 18, 0, 0, 0),
                            Nome = "Convite para retorno",
                            TextoMensagem = "Oi {Nome}! Sentimos sua falta na igreja. Que tal nos visitar novamente neste domingo? Será um prazer recebê-lo!"
                        });
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.ConfiguracaoPortal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TempoTransicaoCarrossel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesPortal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TempoTransicaoCarrossel = 5
                        });
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Membro")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.CriancaDetalhe", b =>
                {
                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Alergias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RestricoesAlimentares")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalaId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PessoaId");

                    b.ToTable("CriancasDetalhes");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.DestaqueSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("DestaquesSite");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Enquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("PermitirMultiplaEscolha")
                        .HasColumnType("bit");

                    b.Property<bool>("PermitirVotoAnonimo")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Enquetes");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.EnqueteOpcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnqueteId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EnqueteId");

                    b.ToTable("EnqueteOpcoes");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.EnqueteVoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnqueteId")
                        .HasColumnType("int");

                    b.Property<int>("EnqueteOpcaoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeAnonimo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnqueteId");

                    b.HasIndex("EnqueteOpcaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EnqueteVotos");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagemDestaque")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.GaleriaFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoDiretorio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CategoriaMidiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemDestaque")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuantidadeFotos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaMidiaId");

                    b.HasIndex("EventoId");

                    b.ToTable("GaleriasFotos");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.HubCasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbertoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Anfitriao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("LiderId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TimoteoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbertoPorId");

                    b.HasIndex("LiderId");

                    b.HasIndex("TimoteoId");

                    b.ToTable("HubCasas");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.InscricaoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ObservacoesInternas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuantidadeAcompanhantes")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId", "WhatsApp");

                    b.ToTable("InscricoesEventos");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.KidsCheckin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CheckinByPessoaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckoutByPessoaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodigoSessao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CriancaPessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CheckinByPessoaId");

                    b.HasIndex("CheckoutByPessoaId");

                    b.HasIndex("CodigoSessao");

                    b.HasIndex("CriancaPessoaId", "Status");

                    b.ToTable("KidsCheckins");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.KidsNotificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriancaPessoaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ResponsavelPessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CriancaPessoaId", "Status");

                    b.HasIndex("ResponsavelPessoaId", "Status");

                    b.ToTable("KidsNotificacoes");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.MensagemAgendada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfiguracaoMensagemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogErro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TextoFinal")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("VisitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracaoMensagemId");

                    b.HasIndex("VisitanteId");

                    b.ToTable("MensagensAgendadas");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaNoticiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Texto")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaNoticiaId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.PessoaPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoasPerfis");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.ResponsavelCrianca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CriancaPessoaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Parentesco")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PodeRetirar")
                        .HasColumnType("bit");

                    b.Property<int>("ResponsavelPessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelPessoaId");

                    b.HasIndex("CriancaPessoaId", "ResponsavelPessoaId");

                    b.ToTable("ResponsaveisCriancas");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmailLogin")
                        .IsUnique();

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Visitante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVisita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Visitantes");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Voluntario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("EquipeId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.CriancaDetalhe", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("CriancaDetalhe")
                        .HasForeignKey("SistemaIgreja.Domain.Entities.CriancaDetalhe", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.EnqueteOpcao", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Enquete", "Enquete")
                        .WithMany("Opcoes")
                        .HasForeignKey("EnqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquete");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.EnqueteVoto", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Enquete", "Enquete")
                        .WithMany("Votos")
                        .HasForeignKey("EnqueteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.EnqueteOpcao", "Opcao")
                        .WithMany("Votos")
                        .HasForeignKey("EnqueteOpcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Enquete");

                    b.Navigation("Opcao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.GaleriaFoto", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.CategoriaMidia", "CategoriaMidia")
                        .WithMany("Galerias")
                        .HasForeignKey("CategoriaMidiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIgreja.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategoriaMidia");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.HubCasa", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Usuario", "AbertoPor")
                        .WithMany()
                        .HasForeignKey("AbertoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Usuario", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Usuario", "Timoteo")
                        .WithMany()
                        .HasForeignKey("TimoteoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AbertoPor");

                    b.Navigation("Lider");

                    b.Navigation("Timoteo");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.InscricaoEvento", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Evento", "Evento")
                        .WithMany("Inscricoes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.KidsCheckin", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "CheckinBy")
                        .WithMany("CheckinsRealizadosPor")
                        .HasForeignKey("CheckinByPessoaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "CheckoutBy")
                        .WithMany("CheckoutsRealizadosPor")
                        .HasForeignKey("CheckoutByPessoaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Crianca")
                        .WithMany("Checkins")
                        .HasForeignKey("CriancaPessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckinBy");

                    b.Navigation("CheckoutBy");

                    b.Navigation("Crianca");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.KidsNotificacao", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Crianca")
                        .WithMany("NotificacoesComoCrianca")
                        .HasForeignKey("CriancaPessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Responsavel")
                        .WithMany("NotificacoesComoResponsavel")
                        .HasForeignKey("ResponsavelPessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crianca");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.MensagemAgendada", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.ConfiguracaoMensagem", "ConfiguracaoMensagem")
                        .WithMany("MensagensAgendadas")
                        .HasForeignKey("ConfiguracaoMensagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Visitante", "Visitante")
                        .WithMany("MensagensAgendadas")
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracaoMensagem");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Noticia", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.CategoriaNoticia", "CategoriaNoticia")
                        .WithMany("Noticias")
                        .HasForeignKey("CategoriaNoticiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaNoticia");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.PessoaPerfil", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Perfis")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.ResponsavelCrianca", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Crianca")
                        .WithMany("ResponsaveisComoCrianca")
                        .HasForeignKey("CriancaPessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Responsavel")
                        .WithMany("ResponsaveisComoResponsavel")
                        .HasForeignKey("ResponsavelPessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crianca");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("SistemaIgreja.Domain.Entities.Usuario", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Visitante", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Visitantes")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Voluntario", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Voluntarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Equipe", "Equipe")
                        .WithMany("Voluntarios")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Voluntarios")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Equipe");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.CategoriaMidia", b =>
                {
                    b.Navigation("Galerias");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.CategoriaNoticia", b =>
                {
                    b.Navigation("Noticias");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.ConfiguracaoMensagem", b =>
                {
                    b.Navigation("MensagensAgendadas");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Enquete", b =>
                {
                    b.Navigation("Opcoes");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.EnqueteOpcao", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Evento", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Checkins");

                    b.Navigation("CheckinsRealizadosPor");

                    b.Navigation("CheckoutsRealizadosPor");

                    b.Navigation("CriancaDetalhe");

                    b.Navigation("NotificacoesComoCrianca");

                    b.Navigation("NotificacoesComoResponsavel");

                    b.Navigation("Perfis");

                    b.Navigation("ResponsaveisComoCrianca");

                    b.Navigation("ResponsaveisComoResponsavel");

                    b.Navigation("Usuario");

                    b.Navigation("Visitantes");

                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Visitante", b =>
                {
                    b.Navigation("MensagensAgendadas");
                });
#pragma warning restore 612, 618
        }
    }
}
