// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaIgreja.Infrastructure.Data;

#nullable disable

namespace SistemaIgreja.Infrastructure.Migrations
{
    [DbContext(typeof(SistemaIgrejaDbContext))]
    partial class SistemaIgrejaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.ConfiguracaoMensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasAposVisita")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HorarioEnvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoMensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesMensagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 6, 26, 23, 10, 6, 153, DateTimeKind.Local).AddTicks(841),
                            DiasAposVisita = 1,
                            HorarioEnvio = new TimeSpan(0, 10, 0, 0, 0),
                            Nome = "Boas-vindas",
                            TextoMensagem = "Olá {Nome}! Que alegria ter você conosco na igreja! Esperamos vê-lo novamente em breve. Deus abençoe!"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 6, 26, 23, 10, 6, 153, DateTimeKind.Local).AddTicks(1116),
                            DiasAposVisita = 7,
                            HorarioEnvio = new TimeSpan(0, 18, 0, 0, 0),
                            Nome = "Convite para retorno",
                            TextoMensagem = "Oi {Nome}! Sentimos sua falta na igreja. Que tal nos visitar novamente neste domingo? Será um prazer recebê-lo!"
                        });
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.MensagemAgendada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfiguracaoMensagemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogErro")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoFinal")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracaoMensagemId");

                    b.HasIndex("VisitanteId");

                    b.ToTable("MensagensAgendadas");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Visitante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVisita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Visitantes");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.MensagemAgendada", b =>
                {
                    b.HasOne("SistemaIgreja.Domain.Entities.ConfiguracaoMensagem", "ConfiguracaoMensagem")
                        .WithMany("MensagensAgendadas")
                        .HasForeignKey("ConfiguracaoMensagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIgreja.Domain.Entities.Visitante", "Visitante")
                        .WithMany("MensagensAgendadas")
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracaoMensagem");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.ConfiguracaoMensagem", b =>
                {
                    b.Navigation("MensagensAgendadas");
                });

            modelBuilder.Entity("SistemaIgreja.Domain.Entities.Visitante", b =>
                {
                    b.Navigation("MensagensAgendadas");
                });
#pragma warning restore 612, 618
        }
    }
}
